version: "3"
services: 
    client:
        image: docker.pkg.github.com/ckanich-classrooms/final-project-ideas-r-us/mefit:v0.0.5
        restart: always
        ports:
            - "80:8080"
        entrypoint: ["npm", "start"]
        environment: 
            - PORT=8080
            - MONGODB_HOST=mongodb
            - MONGODB_PORT=27017
        links: 
            - mongodb
        networks: 
            - mefitnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes: 
            - dbdata:/data/db
        ports:
            - '27017:27017'
        networks: 
            - mefitnetwork
networks: 
    mefitnetwork:
        driver: bridge
volumes:
    dbdata:
        